LearningApp/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import include

app_name = 'LearningApp'


urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    url(r'^courses/$', views.v_courses, name='v_courses'),
    url(r'^courses/(?P<course_id>[0-9]+)/$', views.course_detail, name='course_detail'),

    url(r'^discussions/$', views.v_discussion, name='v_discussion'),
    url(r'^discussions/(?P<discussion_id>[0-9]+)/$', views.discussion_detail, name='discussion_detail'),


    # Profile
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/change-password/$', views.change_password, name='change_password'),

]

MachineEdu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^LearningApp/', include('LearningApp.urls')),
    url(r'^', include('LearningApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LearningApp/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
import datetime



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=15, blank=True)
    phone = models.IntegerField(default=0)
    group_choices = (('Student','Student'),('Teacher','Teacher'),('Other','Other'))
    user_type = models.CharField(max_length=30, choices=group_choices, default='Student')
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return str(self.user.first_name)

class LectureNotes(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    courseName = models.CharField(max_length=20)
    document = models.FileField(upload_to='documents/')
    description = models.CharField(max_length=300, blank=True)
    uploaded_at = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def __str__(self):
         return str(self.courseName)+ ', ' + str(self.document)

class DCategory(models.Model):
    category_name = models.CharField(max_length=20)
    def __str__(self):
         return str(self.category_name)

class Discussion(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    category =  models.ForeignKey(DCategory, on_delete=models.CASCADE, default=1)
    topic = models.CharField(max_length=50)
    sub_topic = models.CharField(max_length=50)
    post = models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def __str__(self):
        return str(self.topic) + " " + str(self.category)

class Blog(models.Model):
    blog_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.blog_name)
class Author(models.Model):
    author_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.author_name)

class Blogpost(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, default=1)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=5000)
    link = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='blog_img', blank=True)

    def __str__(self):
        return str(self.blog) + " " + str(self.title)

class Subject(models.Model):
    subject_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.subject_name)
class Instructor(models.Model):
    instructor_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.instructor_name)
class Provider(models.Model):
    provider_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.provider_name)
class University(models.Model):
    university_name = models.CharField(max_length=50)
    def __str__(self):
         return str(self.university_name)
class Language(models.Model):
    lang = models.CharField(max_length=50)
    def __str__(self):
         return str(self.lang)

class Course(models.Model):
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=300, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=1)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, default=1)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, default=1)
    university = models.ForeignKey(University, on_delete=models.CASCADE, default=1, blank=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, default=1)
    duration = models.CharField(max_length=50)
    cost = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='course_img', blank=True)
    link = models.CharField(max_length=500)

    def __str__(self):
        return str(self.title) + " - " + str(self.subject)

class WishList(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, default=1, on_delete=models.CASCADE)
    wished = models.BooleanField(default=False)
    def __str__(self):
         return str(self.user)+ ', ' + str(self.course)

class FavList(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, default=1, on_delete=models.CASCADE)
    favorited = models.BooleanField(default=False)
    def __str__(self):
         return str(self.user)+ ', ' + str(self.course)

LearningApp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import UserProfile
import datetime
from django.contrib.auth.forms import UserChangeForm









class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
         model = User
         fields = ['username', 'email','first_name', 'last_name']

class UserProfileForm(forms.ModelForm):

    class Meta:
         model = UserProfile
         fields = ['student_id','user_type', 'phone','image']
# Edit Profile ------------------------------------
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

LearningApp/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from .forms import (
    EditProfileForm, UserForm, UserProfileForm,
)
from .models import (
    UserProfile, Course, Discussion
)
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from datetime import datetime

# Edit Profile -----
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse


def index(request):

    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        return render(request, 'index.html')

def v_courses(request):
    courses = Course.objects.all()
    rng = range(0,30)
    context = {
        'courses': courses,
        'rng': rng,
    }
    return render(request, 'course/courses.html', context)

def course_detail(request, course_id):
    coursed = Course.objects.get(pk = course_id)
    context = {
        'coursed': coursed,
    }
    return render(request, 'course/course_detail.html', context)

def v_discussion(request):
    discs = Discussion.objects.all()
    context = {
        'discs': discs,
    }
    return render(request, 'discussion/discussions.html', context)

def discussion_detail(request, discussion_id):
    disc = Discussion.objects.get(pk = discussion_id)
    context = {
        'disc': disc,
    }
    return render(request, 'discussion/discussion_detail.html', context)


def register(request):
    form = UserForm(request.POST or None)
    form2 = UserProfileForm(request.POST or None, request.FILES or None)

    if form.is_valid() and form2.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        userprofile = form2.save(commit=False)
        userprofile.user = form.save(commit=False)

        userprofile.save()
        user = authenticate(username=username, password=password)

    context = {
        "form": form,
        "form2": form2
    }
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('/LearningApp')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/LearningApp/')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'profile/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('LearningApp:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'profile/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/LearningApp/edit')
        else:
            return redirect('/LearningApp/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'profile/change_password.html', args)

LearningApp/templates/profile/change_password.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}
{% load static %}

{% block head %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/profile1.css' %}"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
{% endblock %}
{% endblock %}

{% block body %}
<div class="row my-5">
  <div id="w">
    <div id="content" class="clearfix animated fadeIn">
      <div class="row">
        <div class="col-md-4">
          <div id="userphoto">
            <img src="{%  static 'profile.jpeg' %}" alt="profile" class="img-responsive"/>
          </div>
        </div>
        <div class="col-md-8">
            <form method="post">
              {% csrf_token %}
              <table id="myTable"style="font-size:18px; width:100%;">
                {{ form.as_table }}
              </table>
                <br>
                <a href="{% url 'LearningApp:edit_profile' %}" style="float:right;">
                  <button class="btn btn-xs btn-success" type="submit">Confirm</button>
                </a>
            </form>
            <a href="{% url 'LearningApp:edit_profile' %}" style="float:right;">
              <button class="btn btn-xs btn-danger mx-2" type="button">Cancel</button>
            </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% block scripts %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

<script type="text/javascript">
var help2 = document.getElementsByClassName("helptext");

    $( document ).ready(function() {
        console.log( "ready!" );
        help2[0].style.display = 'none';
    });

</script>


{% endblock %}
{% endblock %}

LearningApp/templates/profile/edit_profile.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}
{% load static %}

{% block head %}
  {% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile1.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  {% endblock %}
{% endblock %}

{% block body %}
<div class="row my-5">
  <div id="w">
    <div id="content" class="clearfix animated fadeIn">
      <div class="row">
        <div class="col-md-4">
          <div id="userphoto">
            <img src="{%  static 'profile.jpeg' %}" alt="profile" class="img-responsive"/>
          </div>
        </div>
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                <table id="myTable"style="font-size:18px; width:100%;">
                  {{ form.as_table }}
                </table>
                <br>
                <button class="btn btn-xs btn-success" type="submit" style="float:right;">Save Changes</button>
            </form>

            <a href="{% url 'LearningApp:view_profile' %}" style="float:right;">
              <button class="btn btn-xs btn-danger mx-2" type="button">Cancel</button>
            </a>

            <a href="{% url 'LearningApp:change_password' %}" style="float:left;">
              <button class="btn btn-xs btn-warning" type="button">Change Password</button>
            </a>
        </div>
      </div>
    </div>
  </div>
</div>

  {% block scripts %}
  <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
      <script type="text/javascript">

      function clear_password() {
        var table, tr, i;
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
          password_tr = tr[3];

          password_tr.style.display='none';
      }
      window.load = clear_password();
      </script>
  {% endblock %}
{% endblock %}

LearningApp/templates/profile/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% load static %}


{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  {% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile1.css' %}"/>
    
  {% endblock %}
{% endblock %}

{% block body %}

<div class="row my-5">
  <div id="w">
    <div id="content" class="clearfix animated fadeIn">
      <div class="row">
        <div class="col-md-4">
          <div id="userphoto">
              <img src="{%  static 'profile.jpeg' %}" alt="profile" class="img-responsive"/>
          </div>
        </div>
        <div class="col-md-8">
            <table style="width:100%; font-size:18px;">
              <tr><th>Username</th><td> {{ user }}</td></tr>
              <tr><th>Name</th><td> {{ user.first_name }}  {{ user.last_name }}</td></tr>
              <tr><th>E-mail</th><td> {{ user.email }} </td></tr>
            </table>
            <br>
            <a href="{% url 'LearningApp:edit_profile' %}" style="float: right;">
              <button class="btn btn-xs btn-info btn-circle" type="button"><i class="fas fa-pencil-alt"></i></button>
            </a>
        </div>
      </div>
      </div>
    </div>

</div>
{% block scripts %}
{% endblock %}

{% endblock %}